
DROP SCHEMA IF EXISTS voting_system CASCADE;
CREATE SCHEMA voting_system;
SET SCHEMA 'voting_system';

CREATE TABLE Poll
(
    id         SERIAL PRIMARY KEY,
    title      VARCHAR(60),
    is_public  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Question
(
    id          SERIAL PRIMARY KEY,
    title       VARCHAR(180),
    description VARCHAR(250),
    poll_id     INT references Poll (id)
);

CREATE TABLE ChoiceOption
(
    id          SERIAL PRIMARY KEY,
    value       VARCHAR(100),
    question_id INT references Question (id)
);

CREATE TABLE Users
(
    id       SERIAL PRIMARY KEY,
    username VARCHAR(40)
);

CREATE TABLE VotedChoice
(
    vote_id          INT references Users (id),
    choice_option_id INT references ChoiceOption (id),
    PRIMARY KEY (vote_id, choice_option_id)
);

CREATE TABLE PollOwnership
(
    user_id INT references Users (id),
    poll_id INT references Poll (id),
    PRIMARY KEY (user_id, poll_id)
);

CREATE TABLE UserGroup
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE UserGroupMembership
(
    user_id  INT REFERENCES Users(id),
    group_id INT REFERENCES UserGroup(id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE PollAccessControl
(
    poll_id INT REFERENCES Poll(id),
    user_id INT REFERENCES Users(id),
    group_id INT REFERENCES UserGroup(id),
    PRIMARY KEY (poll_id, user_id, group_id)
);

--INSERT INTO Poll (title)
--VALUES ('Dupa');
--INSERT INTO Question (title, description, poll_id)
--VALUES ('Question Title', 'Description', 1);
--INSERT INTO ChoiceOption (value, question_id)
--VALUES ('Yes', 1);
--INSERT INTO Users (username)
--VALUES ('Wiktor Belzedup');

---------------------------------- Generated by AI -------------------

-- Insert users
INSERT INTO Users (username) VALUES
('alice'),
('bob'),
('charlie');

-- Insert polls
INSERT INTO Poll (title, is_public) VALUES
('Favorite Programming Language', TRUE),
('Company Satisfaction Survey', FALSE);

-- Insert questions
INSERT INTO Question (title, description, poll_id) VALUES
('Which programming language do you prefer?', 'Pick your most used language.', 1),
('How satisfied are you with your work environment?', '1 = very dissatisfied, 5 = very satisfied', 2);

-- Insert choice options for poll 1
INSERT INTO ChoiceOption (value, question_id) VALUES
('Java', 1),
('Python', 1),
('C++', 1),
('JavaScript', 1);

-- Insert choice options for poll 2
INSERT INTO ChoiceOption (value, question_id) VALUES
('1 - Very Dissatisfied', 2),
('2 - Dissatisfied', 2),
('3 - Neutral', 2),
('4 - Satisfied', 2),
('5 - Very Satisfied', 2);
