DROP SCHEMA IF EXISTS voting_system CASCADE;
CREATE SCHEMA voting_system;
SET SCHEMA 'voting_system';

CREATE TABLE Poll
(
    id         SERIAL PRIMARY KEY,
    title      VARCHAR(60),
    is_private  BOOLEAN NOT NULL DEFAULT FALSE,
    is_closed  BOOLEAN not null DEFAULT false
);

CREATE TABLE Question
(
    id          SERIAL PRIMARY KEY,
    title       VARCHAR(180),
    description VARCHAR(250),
    poll_id     INT references Poll (id)
);

CREATE TABLE ChoiceOption
(
    id          SERIAL PRIMARY KEY,
    value       VARCHAR(100),
    question_id INT references Question (id)
);

CREATE TABLE Users
(
    id       SERIAL PRIMARY KEY,
    username VARCHAR(40)
);

CREATE TABLE VotedChoice
(
    vote_id          INT references Users (id),
    choice_option_id INT references ChoiceOption (id),
    PRIMARY KEY (vote_id, choice_option_id)
);

CREATE TABLE PollOwnership
(
    user_id INT references Users (id),
    poll_id INT references Poll (id),
    PRIMARY KEY (user_id, poll_id)
);

CREATE TABLE UserGroup
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(40) UNIQUE NOT NULL,
    creator_id  INT REFERENCES Users(id) ON DELETE SET NULL
);

CREATE TABLE UserGroupMembership
(
    user_id  INT REFERENCES Users(id),
    group_id INT REFERENCES UserGroup(id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE PollAccessControl (
    id SERIAL PRIMARY KEY,
    poll_id INT NOT NULL REFERENCES Poll(id),
    user_id INT REFERENCES Users(id),
    group_id INT REFERENCES UserGroup(id),

    -- Exactly one of user_id or group_id must be non-null:
    CHECK (
        (user_id IS NOT NULL AND group_id IS NULL) OR
        (user_id IS NULL AND group_id IS NOT NULL)
    ),

    -- Unique constraint on poll_id + user_id (ignoring NULL user_id):
    CONSTRAINT unique_poll_user UNIQUE (poll_id, user_id),

    -- Unique constraint on poll_id + group_id (ignoring NULL group_id):
    CONSTRAINT unique_poll_group UNIQUE (poll_id, group_id)
);

--INSERT INTO Poll (title)
--VALUES ('Dupa');
--INSERT INTO Question (title, description, poll_id)
--VALUES ('Question Title', 'Description', 1);
--INSERT INTO ChoiceOption (value, question_id)
--VALUES ('Yes', 1);
--INSERT INTO Users (username)
--VALUES ('Wiktor Belzedup');

---------------------------------- Generated by AI -------------------

-- Insert users
INSERT INTO Users (username) VALUES
                                 ('alice'),    -- id = 1
                                 ('bob'),      -- id = 2
                                 ('charlie'),  -- id = 3
                                 ('diana'),    -- id = 4
                                 ('eric');     -- id = 5

-- Insert polls
INSERT INTO Poll (title, is_private, is_closed) VALUES
                                                    ('Favorite Programming Language', TRUE, FALSE),   -- id = 1
                                                    ('Company Satisfaction Survey', FALSE, FALSE),    -- id = 2
                                                    ('Team Lunch Options', TRUE, FALSE);              -- id = 3

-- Insert poll ownership
INSERT INTO PollOwnership (user_id, poll_id) VALUES
                                                 (1, 1),
                                                 (2, 2),
                                                 (3, 3);

-- Insert questions
INSERT INTO Question (title, description, poll_id) VALUES
                                                       ('Preferred Language?', 'Which programming language do you prefer the most?', 1),  -- id = 1
                                                       ('Work Satisfaction?', 'Rate your satisfaction at work.', 2),                     -- id = 2
                                                       ('Lunch Spot?', 'Where should we go for lunch on Friday?', 3);                    -- id = 3

-- Insert choice options
-- For poll 1
INSERT INTO ChoiceOption (value, question_id) VALUES
                                                  ('Java', 1),
                                                  ('Python', 1),
                                                  ('C++', 1),
                                                  ('JavaScript', 1);

-- For poll 2
INSERT INTO ChoiceOption (value, question_id) VALUES
                                                  ('1 - Very Dissatisfied', 2),
                                                  ('2 - Dissatisfied', 2),
                                                  ('3 - Neutral', 2),
                                                  ('4 - Satisfied', 2),
                                                  ('5 - Very Satisfied', 2);

-- For poll 3
INSERT INTO ChoiceOption (value, question_id) VALUES
                                                  ('Pizza Place', 3),
                                                  ('Sushi Bar', 3),
                                                  ('Burger Joint', 3);

-- Insert some votes
-- Alice votes Python, id=2
-- Bob votes JavaScript, id=4
-- Charlie votes Java, id=1
INSERT INTO VotedChoice (vote_id, choice_option_id) VALUES
                                                        (1, 2),
                                                        (2, 4),
                                                        (3, 1),
                                                        (4, 7),  -- Diana votes 4 - Satisfied
                                                        (5, 11);-- Eric votes Sushi Bar

-- Create a user group
INSERT INTO UserGroup (name, creator_id) VALUES
                                             ('Dev Team', 1),       -- id = 1
                                             ('HR Department', 2);  -- id = 2

-- Add users to groups
INSERT INTO UserGroupMembership (user_id, group_id) VALUES
                                                        (1, 1), -- alice in Dev Team
                                                        (3, 1), -- charlie in Dev Team
                                                        (5, 1), -- eric in Dev Team

                                                        (2, 2), -- bob in HR
                                                        (4, 2); -- diana in HR

-- Give access to private polls via groups
-- Poll 1 (Favorite Programming Language) -> Dev Team
-- Poll 3 (Team Lunch Options) -> HR Department
INSERT INTO PollAccessControl (poll_id, group_id) VALUES
                                                      (1, 1),
                                                      (3, 2);

-- Give individual access as well
INSERT INTO PollAccessControl (poll_id, user_id) VALUES
    (1, 2); -- Bob gets direct access to Poll 1


